INSERT INTO USUARIOS ( USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES( 'juan', '$2a$10$vHduItvb.QT8seuS.l2eoertrwQXOXiRoURZkr9CCPz2dstWSYAwW', true, 'Juan Francisco', 'Jiménez Pérez', 'jfjimenezp@gmail.com');
INSERT INTO USUARIOS ( USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES( 'admin', '$2a$10$KPU9tUDFmDL9trd2w3xHLe7sqMv1O4aVchgSpcc5NUAQPYSDm.Z.6', true, 'Pedro', 'Duque', 'pduque@gmail.com');
INSERT INTO USUARIOS ( USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES( 'mama', '$2a$10$K8fq4l1US.OQRQOyPfx02.K.qtUf1bQhz.mv26KhEFiaY8YH5rUtq', true, 'Mama', 'Diedhou', 'diedhou@gmail.com');

INSERT INTO ROLES (NOMBRE) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (NOMBRE) VALUES ('ROLE_USER');

INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1,1);
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1,2);
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (2,1);
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (3,2);

