INSERT INTO USUARIOS ( USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES( 'juan', '12345', 1, 'Juan Francisco', 'Jiménez Pérez', 'jfjimenezp@gmail.com');
INSERT INTO USUARIOS ( USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES( 'admin', '222222', 1, 'Pedro', 'Duque', 'pduque@gmail.com');
INSERT INTO USUARIOS ( USERNAME, PASSWORD, ENABLED, NOMBRE, APELLIDOS, EMAIL) VALUES( 'mama', '23232', 1, 'Mama', 'Diedhou', 'diedhou@gmail.com');

INSERT INTO ROLES (NOMBRE) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES (NOMBRE) VALUES ('ROLE_USER');

INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1,1);
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1,2);
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (2,1);
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (3,2);

